name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        python-version: ["3.10"] 

    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  

      - name: Run Pytest with secrets
        env:
          API_ID_PAGINA_FACEBOOK: ${{ secrets.API_ID_PAGINA_FACEBOOK }}
          API_KEY: ${{ secrets.API_KEY }}
          API_TOKEN_PAGINA: ${{ secrets.API_TOKEN_PAGINA }}
          CANAL_LANCAMENTOS: ${{ secrets.CANAL_LANCAMENTOS }}
          CANAL_TAGS: ${{ secrets.CANAL_TAGS }}
          CANAL_TESTES: ${{ secrets.CANAL_TESTES }}
          URI_ATLAS: ${{ secrets.URI_ATLAS }}
        run: |
          export PYTHONPATH=$(pwd)
          python -m pytest -v